### PR TITLE
My feature

### PR DESCRIPTION
**Pull request by kessio**
HelloMicroverse-project is an HTML, CSS project with a homepage and a CSS styling for the homepage. The project uses linter to flag programming errors, bugs, stylistic errors, and suspicious constructs. It also has a .gitignore file that tells Github which files to hide when committing the project. The project tests one's knowledge in writing clear, professional commit messages and READme.

### CODE REVIEW

**Review by ishimwezachee — CHANGES_REQUESTED** [review]
Hi @kessio , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Linters are passing ✔️
The project is running successfully ✔️

## Required Changes ♻️
- [ ] Your ranch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section').
- [ ]  Your pull request should a descriptive title, and a well-detailed description that summarizes the tasks that you've worked on. 
- [ ] You should add your social media into your readme file in the author section. 
image
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kessio** [comment]
@ishimwezachee Kindly do you mean branch when you say ranch? If so does that mean I will need to rename my branch or start over by creating another branch?

**Comment by ishimwezachee** [comment]
> @ishimwezachee Kindly do you mean branch when you say ranch? If so does that mean I will need to rename my branch or start over by creating another branch?

HI @kessio, I am sorry for my typo error, if you have a way of renaming your branch, that's will be awesome, but if not just leave it the way it is, and next time remember to use the right branch name.

**Comment by kessio** [comment]
@ishimwezachee No problem, thank you for the review. 👍

**Review by tufoinnkuo10 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @kessio 

Your project is complete! Great job for making all the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
